### ISSUE TITLE
Allow to run several clients instances of BAC0.connect() on the same server

### ISSUE THREAD

**Issue by max13fr** [ChristianTremblay/BAC0#100]
Hello,

I would like to run several clients instances of BAC0 on the same server (to allow debuging on specific device without stopping main production poller).

Is that possible to access to the socket to allow to add REUSE_ADDR & REUSE_PORT ?
Otherwise, is that possible to select another free port ?

Thanks in advance,
Best regards, Max

**Comment by ChristianTremblay** [comment]
I don’t think it’s possible because of the way bacpypes works. Each instance of BAC0 is a BACnet device and needs to always listen to the port. It doesn’t work like a standard TCP connection where we can pause and restart later. That said, you could run a VM, or use another network card.

**Comment by max13fr** [comment]
Bacpypes seems to allow changing port for this case (see http://bacpypes.sourceforge.net/gettingstarted/gettingstarted002.html#changing-ini-files).

The main process would use the default port 47808 and the secondary process on 47809 for example.

**Comment by ChristianTremblay** [comment]
Yes, but as far as I know, if you try to talk to a BACnet router configured on port 47808, it will not answer to your requests on port 47809...

You would need some kind of internal route...

Technically, you can start BAC0 using another port....

And here is what I get

![2ports](https://user-images.githubusercontent.com/6376327/45692820-b59fc480-bb29-11e8-8f7b-e9f9e10f6188.JPG)

**Comment by ChristianTremblay** [comment]
Or inside the same app...
![2networks](https://user-images.githubusercontent.com/6376327/45693063-3b237480-bb2a-11e8-94c2-6dc48a0114db.JPG)

**Comment by max13fr** [comment]
Indeed broadcast features are not working (like whois) because it's always sent to port 47808.
But for interrogation on specific device, it's work like a charm (eg: BAC0.device(ip, id, bacnet)).

It would be perfect if we could reuse port 47808 only for broadcasting part (as we didn't need any routing 
intelligence because it's a broadcast, so it's for everyone).

**Comment by Safrone** [comment]
An (imperfect) solution is to create essentially an API with the main bacnet network process so the read() capabilities can be accessed from another program.

**Comment by ChristianTremblay** [comment]
The API is probably something close to what BACnet/Secure will be...a kind of WebSocket thing....

I tried accessing devices using 2 different BACnet networks and I have not been able to do it. Probably because devices are MSTP device behind a router configured for port 47808. Your use case may be possible using BACnet/IP devices ?
![2networksb](https://user-images.githubusercontent.com/6376327/45704565-3c15cf80-bb45-11e8-9ad1-91a9d5f5944d.JPG)
