### ISSUE TITLE
Can't Read Points From Controller

### ISSUE THREAD

**Issue by hobo0ps** [ChristianTremblay/BAC0#102]
i'm connected to a controller and i want to look for points but nothing comes up:
![image](https://user-images.githubusercontent.com/6118643/45713806-57c7b700-bbd3-11e8-8bb6-e7e4e601550c.png)
It seems to be connecting to the controller but it's not reading the points.
do you know what could be causing this?

**Comment by ChristianTremblay** [comment]
Can you read the object list ?
```
bacnet.read('192.168.2.100 device 2100 objectList')
```

BAC0 is actually limited to analog, binary and multistate variables when defining devices. Other variables can be interacted with using **bacnet.read** or **bacnet.write** using bacpypes syntax.

So if the list is empty, or do not contain AV, AI, AO, MV, MI, MO or BI, BV, BO... you'll end with an empty device.

**Comment by hobo0ps** [comment]
It's an Innotech Omni c20 BEMS connected to a solar system at a prominent educational institution. I used YABE on it and got nothing, then I used the cimetrics explorer and got a whole bunch of output, maybe it has some sort of nonstandard format? It does have ip/mstp capability, but has a good number of points with things connected to them.
Unfortunately I didn't save it and won't be able to get back out there till Monday (australia).

**Comment by hobo0ps** [comment]
Could you please provide the correct syntax for reading the data within these 3 "file" objects?
I think the object list may be contained within them.
I've tried many iterations of the below but I can't figure it out:
![bac0 read file](https://user-images.githubusercontent.com/6118643/45861756-bfd3f400-bdb1-11e8-8060-30e7eb0cb3e7.PNG)

**Comment by Safrone** [comment]
the syntax is: 
`.read(<IP> <objectType>  <objectAddress> <propertyType> <index>)`
when you do device 2100 you are saying read properties from objectType: device objectAddress: 2100. the objectList tells you what objectType + objectAddresses are associated to the device.

to actually read the values from the points in objectList you would use them as your objectType and objectAddress:

`bacnet.read('192.168.2.100 file 1 <property>')`

this site gives a good list of what properties are available for each objectType: http://www.bacnet.org/Bibliography/ES-7-96/ES-7-96.htm

for file objects (table 5 on the site) it seems like these are the properties:

AtomicReadFile | C | Requests part or all of a File object's file.
AtomicWriteFile | C | Writes to part or all of a File object's file.

(they would probably be written as: `atomicReadFile` given how the rest of the requests work)

so I would try:

`bacnet.read('192.168.2.100 file 1 atomicReadFile')`

**Comment by hobo0ps** [comment]
Not quite, but I feel we're getting close:
![bac0 read file 2](https://user-images.githubusercontent.com/6118643/45906729-9c07c100-be38-11e8-8f5f-4773cc345f75.PNG)

**Comment by Safrone** [comment]
this happened because `atomicReadFile` isn't registered in bacpypes. If you look in `bacpypes/object.py` you will see what is available for different object types (`file` in your case)


```
# .../site-packages/bacpypes/object.py:1482
@register_object_type
class FileObject(Object):
    objectType = 'file'
    properties = \
        [ ReadableProperty('fileType', CharacterString)
        , ReadableProperty('fileSize', Unsigned)
        , ReadableProperty('modificationDate', DateTime)
        , WritableProperty('archive', Boolean)
        , ReadableProperty('readOnly', Boolean)
        , ReadableProperty('fileAccessMethod', FileAccessMethod)
        , OptionalProperty('recordCount', Unsigned)
        ]
```

so try those properties. Hopefully that works

**Comment by hobo0ps** [comment]
Thank you so much for the help. I think that those 3 files are indeed the only points on an improperly configured controller:
![bac0 filetype](https://user-images.githubusercontent.com/6118643/46008150-4add2300-c0ff-11e8-9c39-3c52a39cd9a5.PNG)
