### ISSUE TITLE
long term trending on pi

### ISSUE THREAD

**Issue by bbartling** [ChristianTremblay/BAC0#104]
Hello,

I am attempting to use BAC0 on pi for some long term trending with trending intervals of 15 minutes and a save to SLQlite option. First of all I am scratching my head on how to create a .py file and run a script as I dont think IPython/Jupyter notebooks is an option on raspberry pi.

I have a post here on raspberry stack exchange for using a crontab service to run a .py file every 15 (or maybe even 5) minutes but I am having some issues. It works just fine in terminal running the .py file but I cant get it to work with a crontab service.
https://raspberrypi.stackexchange.com/questions/89228/crontab-schedule-py-file?noredirect=1#comment142588_89228

If I scratch the crontab service idea and just try to do a loop program to save the SQLite db, it appears that the bacnet device is still getting polled at the default 10 second interval even if I define `poll=300`. Just out of curious if the bacnet device polling is every 10 seconds can the pi B+ run out of memory? Does it only save data to the microUSB card during the `.save()` else it holds the data in the computer memory?

![image](https://user-images.githubusercontent.com/29737117/46087623-57e62a80-c170-11e8-98eb-878e40959a9c.png)

Any tips are greatly appreciated for a best practice!
```
import BAC0
import pandas as pd
import time
import datetime


bacnet = BAC0.connect(ip='10.30.4.104/16')
hws = BAC0.device('100:99', 30099, bacnet, poll=300)

def terminate():
	controller.save()
	time.sleep(2)
	bacnet.disconnect()
	print("Its over..." , datetime.datetime.now())

for i in range(5):
	hws.save()
	print("DB saved: " , datetime.datetime.now())
	time.sleep(900)

terminate()
```

I also notice that if I define the SQLite db name, I get an error as well on pi with a similar script using something like `hws.save(db='test')`. Eventually I would like to create a script that could poll multiple BACnet devices but save to the same db.

Thank you so much for creating a such a cool tool!
Cheers,
Ben

**Comment by bbartling** [comment]
One update is attempting to run the crontab  service again with executing this .py file every 15 minutes.

```
import BAC0

bacnet = BAC0.connect(ip='10.30.4.104/16')
hws = BAC0.device('100:99', 30099, bacnet, poll=300)
hws.save()

bacnet.disconnect()
```

But I get an error that 'sql' is not defined.
![image](https://user-images.githubusercontent.com/29737117/46214992-eb029a00-c301-11e8-9fda-0582c8268d2f.png)

And if I give a db name with `hws.save(db='testnew')`, I get a keyword error:
![image](https://user-images.githubusercontent.com/29737117/46215134-387f0700-c302-11e8-80c9-e0840fc84c77.png)


Another odd thing is if I run the same exact script in python 3.6 (berry Conda) a BAC0 attribute error happens... Thanks any tips help if I am doing something goofy on my end.
![image](https://user-images.githubusercontent.com/29737117/46215250-8a279180-c302-11e8-832e-409900ef8d40.png)

Here is some screenshots of the python versions for 3.5 & 3.6
![image](https://user-images.githubusercontent.com/29737117/46215611-716bab80-c303-11e8-830d-0bc4d33177cc.png)
![image](https://user-images.githubusercontent.com/29737117/46215634-80525e00-c303-11e8-9082-c9db8ec3e19b.png)

![image](https://user-images.githubusercontent.com/29737117/46215568-5600a080-c303-11e8-921b-a64b44b566ca.png)

**Comment by ChristianTremblay** [comment]
@bbartling  What if ? 
```
import BAC0

bacnet = BAC0.connect(ip='10.30.4.104/16')
hws = BAC0.device('100:99', 30099, bacnet, poll=0)
hws.save()

bacnet.disconnect()
```

Polling is not necessary as the script will run every 15 minutes....

(be sure to use an updated version of BAC0.... recently fixed a bug with poll argument.)

**Comment by bbartling** [comment]
Hi Christian,

I did a pip uninstall BAC0 then pip install BAC0 on pi but it seemed to install the same exact version. I removed the `pole` like you mentioned as a Crontab service will just execute the file every 15 minutes... Here is some screenshots when I run the script in 3.5 & 3.6. Thanks any tips help! Is there a developer version I could try if I git clone BAC0? No rush on this either thanks...

![image](https://user-images.githubusercontent.com/29737117/47024248-e8d47400-d126-11e8-89bc-7a844fac186a.png)

**Comment by ChristianTremblay** [comment]
You should be at 0.99.943.... you may have to repeat pip uninstall BAC0 a few times....until there nothing left

**Comment by ChristianTremblay** [comment]
You may also check if sqlite3 is installed

**Comment by bbartling** [comment]
Hi Christian,

I did install slqlite 3 as recommended:
![image](https://user-images.githubusercontent.com/29737117/47026893-0e17b100-d12c-11e8-9b0d-9602bd8857fb.png)

and I did uninstall a few times then reinstall BAC0 to revision 99.943 but I still have the same issues:
![image](https://user-images.githubusercontent.com/29737117/47026815-eb859800-d12b-11e8-9d0b-54e7bb6d9877.png)

**Comment by ChristianTremblay** [comment]
Yeah but look into your corn Job....version 934
Can you send me the cron job ?

**Comment by ChristianTremblay** [comment]
!!! Hoops.... I see what’s wrong with 3.6...
I’ve broken something in the address handling.... give me a few minutes

**Comment by ChristianTremblay** [comment]
@bbartling just published a hot fix on Pypi.... 944

**Comment by Safrone** [comment]
also, use `pip3.5` or `pip3.6 install BAC0` as the regular `pip` will go to your default python (which could be 2.7). You can see the BAC0 version is still 0.99.934 in the latest post.

**Comment by bbartling** [comment]
Just for fun I have a new Windows 10 laptop and I installed the latest version of anaconda on it which is 3.7... And I also did a `!pip install BAC0`

Im still having issues trying to get anything to work. It appears to create an SQLite db without a name and there is no data in it when I attempt to browse with SQLite db browser.

![image](https://user-images.githubusercontent.com/29737117/47172637-a7cc9300-d2d1-11e8-93b4-5f1ac6b97344.png)


If I am on a full blown computer and attempt to use the full version of BAC0... In the screen shot above why is it showing Lite version?
![image](https://user-images.githubusercontent.com/29737117/47172791-072aa300-d2d2-11e8-8dc2-5462876e8d98.png)

Thanks for your time & help

**Comment by ChristianTremblay** [comment]
Regarding "Complete" vs "Lite"
You probably are missing some modules... 
To run Complete you need  :  
* Bokeh
* Pandas
* Flask
* flask_bootstrap

**Comment by bbartling** [comment]
Hi Christian, I needed flask_bootstrap to get the full version working..

Am I doing anything wrong that BAC0 is disconnected? Is it not finding the device? If the code is Ok, I wonder if there is something wrong on the Niagara side that it isn't connecting... In Niagara the controller is online and points look Ok.

![image](https://user-images.githubusercontent.com/29737117/47298987-c0dd8880-d5de-11e8-8b1c-05ab87f09cc8.png)


![image](https://user-images.githubusercontent.com/29737117/47299001-cd61e100-d5de-11e8-9def-a6083fefae20.png)

![image](https://user-images.githubusercontent.com/29737117/47299586-2b42f880-d5e0-11e8-9fde-5bcbe9fc777d.png)

**Comment by ChristianTremblay** [comment]
Router enabled on Jace ? 
IP port enabled ?
Same subnet ?

**Comment by bbartling** [comment]
Hi Christian, Yes router is enabled on JACE as well as IP port...
![image](https://user-images.githubusercontent.com/29737117/47436440-20b56a00-d76c-11e8-8e0c-9bea22dcff85.png)


Boiler controller is online thru an MSTP trunk on JACE n4:
![image](https://user-images.githubusercontent.com/29737117/47436395-0e3b3080-d76c-11e8-8ab2-b405f9a931c1.png)

IP configurations of the JACE:
![image](https://user-images.githubusercontent.com/29737117/47436897-0c25a180-d76d-11e8-9225-db7c8eeca4ad.png)

IP configuration for my laptop that is also running BAC0 & workbench simultaneously. I do notice that there is two gateway addresses on my laptop IP config. But workbench seems to work just fine connecting to the JACE. -Also I think someone may have switched the Jace station to SSL recently too
![image](https://user-images.githubusercontent.com/29737117/47436954-295a7000-d76d-11e8-8a84-6b81174c8e40.png)


I also rebooted the JACE thru platform just to try something and it didn't seem to help... Im also on a new windows 10 laptop trying this Vs pi where the most recent version of anaconda is 3.7... Any tips help thanks for your time..

Not sure why it shows disconnected... But I maybe able to switch gears and attempt to us pyhaystack for what I would like to try until my computing skills are up to par...
![image](https://user-images.githubusercontent.com/29737117/47437180-a259c780-d76d-11e8-85d7-f0a4111c2471.png)

**Comment by ChristianTremblay** [comment]
The new version include a timeout on requests, This will help in long term tasks. Please try and give me feedback. Thanks

**Comment by bbartling** [comment]
👍
