### ISSUE TITLE
All properties of point objects not supported like write, alarm etc

### ISSUE THREAD

**Issue by sandhiya88** [ChristianTremblay/BAC0#116]
I am trying to automate testing of my bacnet controller device. I need to check all the point objects as per ASHRAE standards and could not find many of them. Also,many properties of the point objects are not supported in the BAC0/Bacpypes library. please advice.

**Comment by ChristianTremblay** [comment]
Maybe my description needs clarification. But I built BAC0 to be able to test sequences of operation. Not to test a device for BTL compliance.
I mean by that that when I program a sequence using a controller let say for a cleanroom AHU, I can fully test my sequence before installing anything on site. I can simulate inputs, outputs, turn the fan status On when I command the Fan On... etc.

As you point, BAC0 is built on top of bacpypes and any points that would not be supported should be reported to Joel Bender (maintainer of bacpypes).

I'm slowly implementing more and more objects as time goes but I'm not actually moving BAC0 to be a BTL compliance tool.
