### ISSUE TITLE
Still unable to extract the result. plz help

### ISSUE THREAD

**Issue by sandhiya88** [ChristianTremblay/BAC0#118]
BAC0 do not support every points actually.

What you get are bacpypes objects that can be explored (ex. using debug_contents() on them). I want BAC0 to convert to "human readable" python variable things we read over BACnet. An example is the trendLog object... which I convert to Pandas series. 

I'm open to any PR implementing new objects in BAC0.

_Originally posted by @ChristianTremblay in https://github.com/ChristianTremblay/BAC0/issues/115#issuecomment-434686159_

**Comment by sandhiya88** [comment]
On using debug_contents(), I m able to get the value displayed at the python console. But I want it as data for further checking and usage in my code. Could you pls let me know how to do that. Else I should be making changes in the bacpypes constructeddata.py file which I m not sure is the right way. Kindly share your suggestions.

**Comment by sandhiya88** [comment]
Could you pls share the steps how you converted the trendlog to readable format. Mybe even I have to do the same with the TimeStamp object. pls share your views.

**Comment by ChristianTremblay** [comment]
Have a look here : 
https://github.com/ChristianTremblay/BAC0/blob/master/BAC0/core/devices/Trends.py#L96

A lot of trials and errors

**Comment by ChristianTremblay** [comment]
I usually use Jupyter Notebook to explore.... or ipython... once I extract the data I need, I take the code and include that to a module.

**Comment by sandhiya88** [comment]
I tried the same. It actually getting printed to console, I'm unable to get the results as a data to take it further and work on. Could you help.

**Comment by ChristianTremblay** [comment]
@sandhiya88 do you still need help or is this fixed ?

**Comment by ChristianTremblay** [comment]
Work on trends continue, https://github.com/ChristianTremblay/BAC0/tree/develop allow direct access to trendlog from the device. Docs will follow.

Closing this issue, if you need further assistance, re-open or create another issue.
