### ISSUE TITLE
Can't read binaryValue

### ISSUE THREAD

**Issue by liquidOperator** [ChristianTremblay/BAC0#124]
Only when reading a binaryInput object, I experience the following error:
InvalidTag: enumerated application tag required
It is working fine with multiStateValue, analogInput, analogValue, characterstringValue.
I'm using the bacnet simulator available with Yabe (https://sourceforge.net/projects/yetanotherbacnetexplorer/)
There is a full output attacched.
[cantReadBinaryValue.txt](https://github.com/ChristianTremblay/BAC0/files/2707884/cantReadBinaryValue.txt)
I'm using BAC0 0.99.944

**Comment by ChristianTremblay** [comment]
I suspect a divergence between YABE ways of making the binaryInput and bacpypes reading of this kind of data.
Honestly I never saw this error in the field with real devices.

**Comment by liquidOperator** [comment]
I confirm that the problem is Yabe.
I tested my code with some devices and it runs without errors.

**Comment by ChristianTremblay** [comment]
And eventually you’ll stop using YABE :-)
