### ISSUE TITLE
Call to pandas causes a failure in `create_dataframe/2`

### ISSUE THREAD

**Issue by Kartstig** [ChristianTremblay/BAC0#139]
I'm getting an error on the following line:
https://github.com/ChristianTremblay/BAC0/blob/master/BAC0/core/devices/Trends.py#L112

Can this call be incorporated inside the check on [L122](https://github.com/ChristianTremblay/BAC0/blob/master/BAC0/core/devices/Trends.py#L112) to ensure Pandas exists?

**Comment by ChristianTremblay** [comment]
Yep, you are right.. there is a flaw here...

**Comment by ChristianTremblay** [comment]
Can you please test branch issue-139 ?

**Comment by ChristianTremblay** [comment]
Does this solve your issue ?

**Comment by Kartstig** [comment]
Sorry for the delay. I'll test your branch tonight and see if it's resolved

**Comment by ChristianTremblay** [comment]
so ?

**Comment by Kartstig** [comment]
It's solved. Closing this issue! Thank you!!
