### ISSUE TITLE
Install error using Python 3.7

### ISSUE THREAD

**Issue by wayne1203** [ChristianTremblay/BAC0#147]
Hi, 

I tried to run setup.py or using pip install BAC0 in python 3.7 but will got same error "Systax error"
It will be work when I using python 3.6

**Comment by ChristianTremblay** [comment]
Any details on the error ? I'm running 3.7 here not problem.

**Comment by wayne1203** [comment]
Error message like #45 
But I'm using Ubuntu 18.04 LTS
I tried use develop brunch to run install but same error as well

**Comment by ChristianTremblay** [comment]
Absolutely sure it's not Python 2 that get triggered ?

**Comment by wayne1203** [comment]
Pretty sure I'm running python 3.7.x
I checked python version (-V) before I run the setup.py

**Comment by ChristianTremblay** [comment]
Can you please provide screen shots ?

**Comment by wayne1203** [comment]
Sure
<img width="684" alt="螢幕截圖 2019-07-30 下午2 58 00" src="https://user-images.githubusercontent.com/8578341/62107783-f08e8f00-b2da-11e9-9dcb-c6b45239ef1e.png">

**Comment by ChristianTremblay** [comment]
Haaaa ! sudo !
If you “sudo Python -v” you will probably see Python 2 ;-)

Try installing without sudo. In fact, you should never sudo pip. It won’t point to your user install folder but will target the system install.

**Comment by wayne1203** [comment]
Oh... Yes, it's show 2.7.15+
I got Permission denied if I not use sudo

<img width="919" alt="螢幕截圖 2019-07-30 下午5 33 03" src="https://user-images.githubusercontent.com/8578341/62118463-4b7eb100-b2f0-11e9-8ed9-0de10e83f082.png">

**Comment by ChristianTremblay** [comment]
Then you get some choices... you could force python3 with sudo....`sudo python3 setup.py install`
Or grant yourself permission...
Or I think there is a —user flag possible (?) never used it
Or use Virtual Environments. The latter being probably the best solution.

See : https://docs.python-guide.org/dev/virtualenvs/

**Comment by ChristianTremblay** [comment]
On Ubuntu I have always used Anaconda... was easier as they provide everything I needed.
(www.anaconda.org)

**Comment by wayne1203** [comment]
Thank you for your support.
