### ISSUE TITLE
Run full version on a pi?

### ISSUE THREAD

**Issue by bbartling** [ChristianTremblay/BAC0#150]
Hi Christian 

Can the full version run on a pi?

For a job we have to make an energy dash board to display building power and fuel use. 

I was hoping to do most calcs for energy on the jace and then use an export table for bac0. 

Then hopefully some basic math in python to compile units of power into energy. IE, kW to kWh..

Could this data then be displayed thru bac0 bokeh server on a pi in a control panel?

Thanks, 
Ben

**Comment by ChristianTremblay** [comment]
Yes. Use berryconda to install Pandas and Bokeh... or something like that (miniconda). Those are already compiled for the RPi in those packages.

**Comment by bbartling** [comment]
Cool. Is it also possible for BAC0 to log calculated values in Python?

For example if I get electrical kW by polling the JACE export table, and then in Pandas resample previous days kW data to calculate kWh, would I be able to use BAC0 bokeh server to display that data thru a web browser connection to the pi? Or is it only data that is being polled thru BACnet..?

**Comment by bbartling** [comment]
Hopefully that makes sense!

**Comment by ChristianTremblay** [comment]
Hummm..... i never thought of that but I think it should be possible. Trends are sent to your BACnet instance. You must give a pandas série. Let me check the code.

**Comment by ChristianTremblay** [comment]
So... BAC0 wants the format of the thing sent to be a point. With name,units,properties and history. Pretty sure you could define a point (kind of virtual point) that would point to your result with the history. We should make some tests. When we find a good way, let’s build something convenient.

**Comment by ChristianTremblay** [comment]
I’ll close this one and open a new one with the trend request

**Comment by bbartling** [comment]
Hi Christian, which new issue with the trend request was opened after this one was closed?

**Comment by ChristianTremblay** [comment]
https://github.com/ChristianTremblay/BAC0/issues/154 ?
