### ISSUE TITLE
BACnet issue

### ISSUE THREAD

**Issue by NagarjunaReddy1242** [ChristianTremblay/BAC0#166]
Hi sir,
I was installed BAC0 on my ubuntu. and i was connected bacnet device  as a TCP connection.
i tried 
like below program
import BAC0
bacnet=BAC0.connect(ip='169.254.24.7/24')
 iam getting error
BAC0.core.io.IOExceptions.InitializationError: IP Address provided (169.254.24.7) invalid.

how to solve this error.

**Comment by ChristianTremblay** [comment]
By providing a valid IP. Your interface seems to be disconnected.

**Comment by NagarjunaReddy1242** [comment]
Sir if i provide a valid IP what can i get the details given by
bacnet.whois() and can you please give the small program to read of our
bacnet register mapping. Please find below data mapping.


1,AV-11, 4264_1_1, Output Apparent Power Rating (System
Information->Ratings)

2,AV-12, 4103_1_1, System Input Nominal Frequency (System
Information->Ratings)

3,AV-13, 4102_1_1, System Input Nominal Voltage (System
Information->Ratings)

4,AV-14, 4261_1_1, System Output Nominal Frequency (System
Information->Ratings)

5,AV-15, 4260_1_1, System Output Nominal Voltage (System
Information->Ratings)


Please sir i need your help in this regard.

**Comment by ChristianTremblay** [comment]
Not sure I understand this part in your description  "4260_1_1"
Is your device IP or MSTP
What is the network number ?
What is the device ID of the device ?

**Comment by ChristianTremblay** [comment]
If still needed, please reopen
