### ISSUE TITLE
How to get the value of the points given by an object_list when using Device?

### ISSUE THREAD

**Issue by HAMH96** [ChristianTremblay/BAC0#170]
I am trying to get the value of some points of a device, I don't know if I am giving the object list uncorrectly, because I don't know what is the correct syntax to do it, my code is the following:

bacnet = BAC0.connect(ip='192.168.0.101/24')
my_obj_list = [('digitalInput',1),('digitalInput',2),('digitalInput',3)] 
controller  = BAC0.device('192.168.0.201/24',32403,bacnet, object_list=my_obj_list)

the code doesn't give any error when running, but I don't know how to get the value of each point, because I didn't give any name or ID, could you please help me?

**Comment by ChristianTremblay** [comment]
Hi, you will need to explore your device first : 

`bacnet.read('192.168.0.201 device 32403 objectList')` will give you the object list of the device.

'digitalInput' is not a valid object in BACnet. You will see 'binaryInput' instead.
Once you have the object list, you will be able to build your custom object list.

If you don't know which one do what, I suggest to define the device once, by default. It will give you all the points. You will then be able to cherry pick the one you need.

`controller = BAC0.device('192.168.0.201',32403,bacnet)`

use `controller.points` for example once it is done.
If you get into troubles here, you can try turning off segmentation (useful for big devices)
`controller = BAC0.device('192.168.0.201',32403,bacnet, segmentation_supported=False)`
This will take forever to create your device, but once done, you will be able to explore it and find the point you really need.
