### ISSUE TITLE
BAC0 to BAC0

### ISSUE THREAD

**Issue by plrosa** [ChristianTremblay/BAC0#173]
I am trying to do bac0 to bac0 using fake sensors. Wondering if it<s possible as I can't figure how to do it..

**Comment by ChristianTremblay** [comment]
Yes it is possible. I do that in the test suite.

You can define 2 BAC0 instances (using 2 IPs OR two different ports)

Have a look to the tests (https://github.com/ChristianTremblay/BAC0/blob/master/tests/conftest.py)
