### ISSUE TITLE
Change point properties 

### ISSUE THREAD

**Issue by San42** [ChristianTremblay/BAC0#182]
Is there a way to change properties like units via BAC0. For example, if (analogInput,3) has an unit in volts and I want to change it to degreeCelcius since I have connected a thermistor to it?

**Comment by ChristianTremblay** [comment]
I'm not aware of devices allowing to do that. Typically, you need a proprietary tool to configure and download the field device.

Some device (like gateways) provide a variable to switch between SI and US for example... but it is not what you request.

As far as I know and see it in the field, BACnet is a way to make devices communicate with each others... not a way to agnostically download any device from any manufacturer to modify their behaviour.
