### ISSUE TITLE
How to get vendorname

### ISSUE THREAD

**Issue by luli440** [ChristianTremblay/BAC0#205]
The vendor name I scanned is an unknown vendor. How can I customize a value for it? Thank you very much
![clipboard](https://user-images.githubusercontent.com/66595084/86453185-f513c100-bd4f-11ea-8449-8d6f16975ec7.png)

**Comment by ChristianTremblay** [comment]
This looks like default bacpypes valus... not BAC0's one.
vendorName is an arguments when defining BAC0 instance.

For bacpypes, it's written in the .ini file I think

**Comment by ChristianTremblay** [comment]
You can get a vendor name for free if you contact ASHREA. (http://www.bacnet.org/VendorID/)

A list can be found here.
http://www.bacnet.org/VendorID/BACnet%20Vendor%20IDs.htm

To read the vendorName, request is : 
```
bacnet.read('Address device deviceId vendorName')

**Comment by luli440** [comment]
> 如果您与ASHREA联系，则可以免费获得供应商名称。（http://www.bacnet.org/VendorID/）
> 
> 列表可以在这里找到。
> http://www.bacnet.org/VendorID/BACnet%20Vendor%20IDs.htm
> 
> 要读取vendorName，请求为：
> 
> ```
> address = 2000:12 # let say it is the address
> deviceid = 5000 #let say this is the deviceID
> bacnet.read(f'{address} device {deviceId} vendorName')
> ```

Thank you very much！
