### ISSUE TITLE
Support for Who-Has Request 

### ISSUE THREAD

**Issue by spokale01** [ChristianTremblay/BAC0#206]
Hello Christian,

It looks that BAC0 do not have support for 'Who-Has' request ?  

I am getting attribute error "AttributeError: 'Lite' object has no attribute 'whohas' "

Can you please provide the support for 'Who-Has' 

Regards,
Sandeep

**Comment by ChristianTremblay** [comment]
On the to-do list... but I lack time.
PR welcome :)

**Comment by ChristianTremblay** [comment]
@spokale01 Done
Checkout develop branch
