### ISSUE TITLE
Errorno 24 : Too many files open

### ISSUE THREAD

**Issue by San42** [ChristianTremblay/BAC0#216]
I am using BAC0 in a code to read a bunch of bacnet points.  I am reading those points every 1 min. Essentially I am using 3 lines of code involving BAC0:
``` 
while True:
 bac=BAC0.lite("192.168.xx.xx")
 value=bac.read(read_string)
 bac.disconnect()
```
It runs for sometime fine(on an average 2-3 days) and then stops with the following exception:
```
Aug 14 15:19:19 raspberrypi python3[26123]:   File "/home/san/AWS/bacnet.py", line 50, in read_val
Aug 14 15:19:19 raspberrypi python3[26123]:     bac=BAC0.lite("192.168.10.3")
Aug 14 15:19:19 raspberrypi python3[26123]:   File "/home/san/AWS/venv/lib/python3.7/site-packages/BAC0/scripts/Lite.py", line 129, in __init__
Aug 14 15:19:19 raspberrypi python3[26123]:     **params
Aug 14 15:19:19 raspberrypi python3[26123]:   File "/home/san/AWS/venv/lib/python3.7/site-packages/BAC0/scripts/Base.py", line 145, in __init__
Aug 14 15:19:19 raspberrypi python3[26123]:     raise InitializationError("Gros probleme : {}".format(error))
Aug 14 15:19:19 raspberrypi python3[26123]: BAC0.core.io.IOExceptions.InitializationError: Gros probleme : Error starting app: [Errno 24] Too many open files
```
I have tried increasing the files limit via ulimit , both the soft and the hard limits, with no success. Any help would be highly appreciated! Thank you!

**Comment by ChristianTremblay** [comment]
Due to the nature of BACnet, BAC0 is a device on the network. Constantly creating it, then disconnecting it goes against the idea of a device, which would constantly disappear from the network.
My recommandation is to start the instance once. Then run all your requests until you are sure the thing is not needed anymore.

```
bac=BAC0.lite("192.168.xx.xx")

while True:
    value=bac.read(read_string)
    # anything you do with value

bac.disconnect()

```

**Comment by San42** [comment]
Thanks for the reply. The snippet of code I provided was an oversimplified version involving multiple scripts and functions. It would be a little difficult to make the changes as you have suggested. I will try it nonetheless and report if the same issue persists.
