### ISSUE TITLE
Write property multiple only sends request for last element in args list

### ISSUE THREAD

**Issue by RachelErin** [ChristianTremblay/BAC0#223]
build_wpm_request resets was[] with each iteration and when the request is created, only sends the last item in the list. In addition, if you move was[] reset to outside the loop, multiple requests for writing to the same object create new object tags for each property request instead of creating a property tag under the existing object. 

https://github.com/ChristianTremblay/BAC0/pull/224

**Comment by ChristianTremblay** [comment]
Thank you very much for taking the time to fix my errors !

I will review that ASAP and this will merge with develop.

This is not a feature I use so chances are that I would never have seen the
flaw.

Le lun. 19 oct. 2020 à 09:18, RachelErin <notifications@github.com> a
écrit :

**Comment by ChristianTremblay** [comment]
Merged https://github.com/ChristianTremblay/BAC0/pull/224
