### ISSUE TITLE
CPU getting to 100% on Linux

### ISSUE THREAD

**Issue by ChristianTremblay** [ChristianTremblay/BAC0#231]
Bug reported by a user by email.

Cuased by task manager thread "not having" time.sleep

**Comment by NubeDev** [comment]
I had the same issue on arm/debian it was unable.

**Comment by ChristianTremblay** [comment]
Can you confirm this is fixed by latest version ?

**Comment by ChristianTremblay** [comment]
Made a few tests and everything seems fine....closing.
