### ISSUE TITLE
device.save failes when pandas is not installed and/or without resampling

### ISSUE THREAD

**Issue by trollkarlen** [ChristianTremblay/BAC0#268]
device.save failed when pandas(looks from the code like its optional) is not installed. 
Due to that point is a dict and not a pandas object that have resample function.

If you disable resampling it failed due to that 'resampling_freq is not set in function backup_histories_df this fail with and without pandas installed.

//T

**Comment by ChristianTremblay** [comment]
Thanks for pointing that. Do you have a suggestion ?

**Comment by ChristianTremblay** [comment]
Keeping that alive

**Comment by trollkarlen** [comment]
Will send a pull request, have not gotten there yet doh.

//T

**Comment by trollkarlen** [comment]
Forgotten this issue, will maka a fix and create a pull request on Monday
in case.
