### ISSUE TITLE
Points.properties.units_state is empty

### ISSUE THREAD

**Issue by zemelLeong** [ChristianTremblay/BAC0#274]
![image](https://user-images.githubusercontent.com/26835087/117908101-835eb900-b30a-11eb-8b0b-f857404dfb57.png)
![image](https://user-images.githubusercontent.com/26835087/117908122-8c4f8a80-b30a-11eb-983d-220467c9ab4f.png)

I test a device found the `Points.properties.units_state` is empty. It will raise `IndexError: list index out of range` exception.

**Comment by ChristianTremblay** [comment]
I should add IndexError to the catch. Thanks
