### ISSUE TITLE
pandas seems to be a requirement but isn't in requirements.txt

### ISSUE THREAD

**Issue by skewty** [ChristianTremblay/BAC0#277]
https://github.com/ChristianTremblay/BAC0/blob/d5aed211b80591a5daacffa5a645dfc51830079c/BAC0/sql/sql.py#L135

**Comment by ChristianTremblay** [comment]
I have not made pandas a requirement as it is not necessarily possible to install it on all plateform easily. 

I'm aware that some feature may not work but until then, I've found that it was better to not prevent the install. And there are lot of features that work without pandas.
