### ISSUE TITLE
Passing of deviceId to "Base" class

### ISSUE THREAD

**Issue by igloodan** [ChristianTremblay/BAC0#287]
Hello everyone,

I can see in the code that when calling `BAC0.lite()`, I can pass a variable number of arguments via `**params` but I don't think these are being used by `Base.__init__()`.

I'm looking to pass an argument in for `deviceId` so that I can specify what is used for communication on the network.

BAC0.lite() doesn't have a `deviceId` argument, just `**params`.
These `**params` are then passed to `Base.__init__()` but (my knowledge here is limited) this isn't parsed as `Base.__init__()` is awaiting a named argument called `deviceId` and doesn't specifically check the passed dict.

Is my understanding here correct, is it possible to specify a device ID with the code as is?

Thanks.

**Comment by ChristianTremblay** [comment]
ex. : device_app = BAC0.lite(deviceId=101)

**Comment by igloodan** [comment]
@ChristianTremblay 
Thanks for your quick response!
My apologies, I was trying this in the `BAC0.device()` function, not the `BAC0.lite()` function.
