### ISSUE TITLE
Test device doesn't show with discover or whois

### ISSUE THREAD

**Issue by vakker** [ChristianTremblay/BAC0#294]
If I create a test device (similarly to how it's done in [conftest.py](https://github.com/ChristianTremblay/BAC0/blob/master/tests/conftest.py):
```
import BAC0

bacnet = BAC0.lite()

device_app = BAC0.lite(port=47809, deviceId=101)

ip = device_app.localIPAddr.addrTuple[0]
boid = device_app.Boid

test_device = BAC0.device(f"{ip}:47809", boid, bacnet, poll=10)

print(bacnet.discover(networks='known'))
print(bacnet.whois())
```

Then it prints the physical devices that I have connected to the network, but not the virtual one. 
Is this intended?

**Comment by ChristianTremblay** [comment]
Yes. Because whois use broadcast on port 47808 by default. And the other device is on port 47809 (because there would be a port clash...)
If you want to test whois, you could use two interfaces orc configure 2 IP in your NIC.

**Comment by vakker** [comment]
@ChristianTremblay great, thanks!
