### ISSUE TITLE
Connect bits to supported object types

### ISSUE THREAD

**Issue by mosterme1003** [ChristianTremblay/BAC0#299]
Hey! When I read the `protocolObjectTypesSupported` property from a device object it returns a list of bits. I have trouble to connect these bits to the respective object types. Is there a way to get like a dictionary with the object type strings or enumerations connected to the bits or similar outputs?

```py
supportedTypes = bacnet.read("10.64.134.162 device 2106201 protocolObjectTypesSupported")
print(supportedTypes)

>> [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0] 
```

I really appreciate your help! Thank you.

**Comment by ChristianTremblay** [comment]
that would be nice :)
Let's put that on the list
