### ISSUE TITLE
Trend Log-Log Device Object Property Write Operation

### ISSUE THREAD

**Issue by VigneshwaranKR** [ChristianTremblay/BAC0#300]
I'm just trying to do write operation for Trend log property Log Device Object Property. I just want to change sub property value called object identifier. There are no proper documentation for this to do write operation. How to do write operation for log device object property for trendlog? @ChristianTremblay

**Comment by ChristianTremblay** [comment]
The object identifier is like a major property for an object and only few controllers on the field will allow that to be changed from an external command. I would be surprised if you make it work... 

On all controllers I know, it's a read-only property
