### ISSUE TITLE
Sending Binary and Multistate "value" as an integer to influxdb

### ISSUE THREAD

**Issue by kushan-26** [ChristianTremblay/BAC0#312]
Hello Christian,

I noticed that the binary and multistate values including the string_value are being sent as a string to influxdb. These point types cannot be plotted for a specific time interval to see a trend or do any aggregation other than "Last" due to this reason. I have twiddle with the code to see if I can get the "value" part as an integer but failed to do so.

Futhermore, I noticed that analogue values show two tables for "value and "string_value" in influxdb raw data. Binary and multistate shows up in a single table. Think the issue lies within how these tables are created or queried in influxdb. I guess the question is how can we create two tables for binary and multistate. 
![Influxdb_binary_points](https://user-images.githubusercontent.com/67067860/149843658-df9551fb-f009-40f1-8851-accf06dd0365.PNG)

Can you think of any solution for this?

**Comment by ChristianTremblay** [comment]
That is not the intent. If you look here : 
```
def clean_value(self, object_type, val, units_state):
        if "analog" in object_type:
            _string_value = "{:.3f} {}".format(val, units_state)
            _value = val
        elif "multi" in object_type:
            _string_value = "{}".format(val.split(":")[1])
            _value = "{}".format(val.split(":")[0])
        elif "binary" in object_type:
            try:
                _string_value = "{}".format(units_state[int(val.split(":"[0]))])
            except:
                _string_value = "{}".format(val.split(":")[1])
            _value = "{}".format(val.split(":")[0])
        else:
            _string_value = "{}".format(val)
            _value = val
        return (_value, _string_value)
```
I create 2 distinct fields, a string_value that is meant to be used by tools that can work with strings... (last value presenting the actual state for example)... and value, which hold the numeric part of the information.

![image](https://user-images.githubusercontent.com/6376327/149863372-86484c3b-f2ea-4c29-bfcf-99c8f359d60b.png)

If filtering by _field : value
![image](https://user-images.githubusercontent.com/6376327/149863460-258ed93f-98e9-4406-a260-54b378a96ae7.png)

Here you can see examples where I use the string value
![image](https://user-images.githubusercontent.com/6376327/149863609-8af016f7-056f-4d5b-ac1a-24b8d482722b.png)

and here
![image](https://user-images.githubusercontent.com/6376327/149863645-ab470912-e2ae-4502-a0d5-eac708e7dd1a.png)

**Comment by kushan-26** [comment]
I do understand the string value and its usage. I'm actually talking about the numeric part of the binary and multistate points. The numeric part is identified as a string in influxdb. If you select a binary point -> value field and try to use the 'mean' aggregate function, you'd see the following error: 'unsupported input type for mean aggregate: string'. Shouldn't that be an integer or double type value?
![string_error](https://user-images.githubusercontent.com/67067860/149870959-ca79c4f8-db74-4caa-8747-ecc90dbe5fe4.JPG)

Also, if you do the same filter (binary point -> value) with the 'last' aggregate function and plot a graph, output the trend is sort of broken because of string numeric values.
![binary_graph](https://user-images.githubusercontent.com/67067860/149871040-90d33951-4935-4771-894f-2484c461834f.JPG)

I tried changing the following lines in bold to convert the string to integer but that broke the _value and only received the '_string_value' part to the database.
        elif "multi" in object_type:
            _string_value = "{}".format(val.split(":")[1])
            _value = **"{}".format(val.split(":")[0])** -> int(val.split(":")[0])
        elif "binary" in object_type:
            try:
                _string_value = "{}".format(units_state[int(val.split(":"[0]))])
            except:
                _string_value = "{}".format(val.split(":")[1])
            _value = **"{}".format(val.split(":")[0])** -> int(val.split(":")[0])

Hope this explains the issue I'm trying to point out.

**Comment by kushan-26** [comment]
@Christian - Actually what I changed in the script did work. It was just an issue with influxdb not being able to handle two data types under the same record in the same bucket. I created a new Bucket and was able to receive both string_value and numeric value as a float type. I've created a pull request with changes to the script.

Just needed a fresh day to think different...lol

Thanks for your help!

**Comment by ChristianTremblay** [comment]
This bug did affect my own DB here and I also have string values instead of `integer`... but there is always a solution !

```
from(bucket: "BAC0")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "Device_5/binaryInput:7")
  |> filter(fn: (r) => r["_field"] == "value")
  |> toInt()
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")
```

`toInt()` convert all `_value` column to int

flux is cool

**Comment by kushan-26** [comment]
That is pretty cool. I did not think about it that way.
