### ISSUE TITLE
Writing Start/Stop date time in trendlog using Python

### ISSUE THREAD

**Issue by VigneshwaranKR** [ChristianTremblay/BAC0#316]
Hello,i'm trying to write Start/Stop date time using bac0 for trendlog.But i couldn't able to do write operation.Can you help me to do write operation for Start/Stop datetime. @ChristianTremblay

**Comment by ChristianTremblay** [comment]
Are you trying to create a local object (trendlog) or writing a trendlog on another device using BAC0 ?

**Comment by VigneshwaranKR** [comment]
> Are you trying to create a local object (trendlog) or writing a trendlog on another device using BAC0 ?
Trying to write a trendlog on another device.
Ex:"192.254.48.24 trendLog 1 startTime 3,3,2003,11,00,00"
