### ISSUE TITLE
Non-Standard port

### ISSUE THREAD

**Issue by ChristianTremblay** [ChristianTremblay/BAC0#318]
From @Safrone on Giitter.

for bacnet = BAC0.connect(ip='192.168.1.225', port=47807)
the address gets encoded as the hex instead of the ip:port which the Address doesn't like

![image](https://user-images.githubusercontent.com/6376327/158088372-d6725b4f-82d3-4ac7-bfc0-6b26fc2af52c.png)

I will ask Joel but I think 47807 is not an acceptable port.... (47808+)

**Comment by Safrone** [comment]
@ChristianTremblay Thanks for creating the issue. From a quick search online it looks like BAC0 - BAC9 (47808-47817) is expected. This may be an edge case of a client of ours not caring/knowing about the "rules". Ultimately I got it working but I had to translate the hex to ip:port for the devices I wanted to read
