### ISSUE TITLE
utcOffset data type wrong

### ISSUE THREAD

**Issue by jshenguru** [ChristianTremblay/BAC0#320]
In BAC0/core/functions/TimeSync.py, the utfOffset() returns a real number while BACnet requires the 'utcOffset' property to be integer. This wrong data type fails the response to the ReadPropertyMultiple for 'all'.

A quick fix would be round() the return value of the utcOffset to integer.

**Comment by ChristianTremblay** [comment]
Do you want to issue a PR ?

**Comment by jshenguru** [comment]
> Do you want to issue a PR ?

A PR is created and waiting for you to merge.
