### ISSUE TITLE
Device responds WhoIs on subnet broadcast with IAm on 255.255.255.255

### ISSUE THREAD

**Issue by jkempf42** [ChristianTremblay/BAC0#322]
So I'm having a problem with the Yabe thermostat simulator (see [here ](https://sourceforge.net/projects/yetanotherbacnetexplorer/)for code) and the Chipkin device simulator (see [here ](https://github.com/chipkin)for code). These are BacNet device simulators which do not use the subnet broadcast (ex. 192.162.3.255) but rather the all points broadcast address (255.255.255.255). I'm running on Ubuntu 20.04 in a VirtualBox VM. The device simulator is running in one VM and the BAC0 controller in another.

The problem is that if I do:

`bacnet=BAC0.connect('192.168.3.4/24')`

No devices are discovered because the devices reply on 255.255.255.255 and BAC0 isn't listening there. If I do:

`bacnet=BAC0.connect('255.255.255.255/24')`

I can discover the devices OK (though the IP address is somehow incorrect) but BAC0 fails to see the return message from readProperty() and writeProperty(). Even though I can see the packets coming back in Wireshark, BAC0 fails to see them.

If I do readProperty() and writeProperty() with the IP address of the device simulator after using the 255x4 address to discover it, the packets come back OK but BAC0 fails to see them.

If I do readProperty() and writeProperty() after doing connect() with the subnet address, the return comes to the subnet address but BAC0 fails to see them.

Any thoughts?

        jak

**Comment by ChristianTremblay** [comment]
It really is a network issue between the VM and your network. Not a BAC0 issue. 
I have no idea why using 255.255.255.255 as an IP work partially. I never tried that and I don't know what it means for/in the network stack/socket...

Normally, BAC0 will listen to both global and subnet broadcast. By telling /24 you use the subnet broadcast which is better in a network than the global version of a broadcast.

You could try to use `bacnet = BAC0.lite(ip="ip/24")`
then `bacnet.whois(global_broadcast=True)` and see what comes up
