### ISSUE TITLE
Cannot import BAC0 in python3.5

### ISSUE THREAD

**Issue by AmauryLFc** [ChristianTremblay/BAC0#327]
After installing BAC0 in python3.5, I cannot import it.
Here is the error I get:

`Python 3.5.10 (default, Jan 15 2022, 19:53:00) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import BAC0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amaurylf/.local/lib/python3.5/site-packages/BAC0/__init__.py", line 18, in <module>
    from .scripts.Base import Base
  File "/home/amaurylf/.local/lib/python3.5/site-packages/BAC0/scripts/__init__.py", line 8, in <module>
    from . import Lite
  File "/home/amaurylf/.local/lib/python3.5/site-packages/BAC0/scripts/Lite.py", line 64, in <module>
    from ..db.influxdb import InfluxDB, ConnectionError
  File "/home/amaurylf/.local/lib/python3.5/site-packages/BAC0/db/influxdb.py", line 41
    flush_interval=getattr(self, "flush_interval", 10_000),
                                                        ^
SyntaxError: invalid syntax`

In influxdb.py, if I change the syntax in lines 41,42,43 and 45, for example from "10_000" to "10000" then it works.

**Comment by ChristianTremblay** [comment]
I do my development with 3.8+... I hesitate to put a lot of effort in keeping everything backward compatible. 

3.5 being EOL... 

I'm open to suggestions though... and PR.

**Comment by AmauryLFc** [comment]
Hi, thanks for the answer,

I figured out that writing numbers with underscore symbols is a feature from python3.6+ but unfortunately we can't upgrade python on our hardware, we are limited to python 3.5

**Comment by ChristianTremblay** [comment]
Do you need all the new features like influxDb ?

If not, maybe cloning an older version would work ?

**Comment by AmauryLFc** [comment]
Indeed we don't need the features kinked to influxDB.

Thanks a lot for your help, we will think about the different options we have.

**Comment by ChristianTremblay** [comment]
Another idea. In older RPi version I used Berryconda which was based on Python3.6 so I didn't have to tamper with the OS Python.
