### ISSUE TITLE
Reading BACnet device when multiple devices exist under the same IP

### ISSUE THREAD

**Issue by Paul-AJ** [ChristianTremblay/BAC0#339]
Hello, 

I'm new to BACnet and BAC0 so maybe there's some information I'm missing. I'm on a BACnet/IP network, and I was wondering if there is a way to read from a specific BACnet device when multiple devices exist under the same IP? 

Originally I thought doing something like this would create a request and read from a BACnet device 115520:
```
bacnet = BAC0.lite(ip='172.16.1.152')
device = BAC0.device('172.16.1.2', 115520, bacnet)
device.read_property(('analogInput', 1, 'presentValue'))
```
However, I found out that this is simply the same thing as:   
```
bacnet.read('172.16.1.2 analogInput 1 presentValue')
```
Which does not take into account which device on IP 172.16.1.2 it's trying to read.
Essentially, Is it possible to specify what device I am trying to read from? If not is there a way about handling this situation some other way? 

Thank you.

**Comment by ChristianTremblay** [comment]
Can you be more specific ? Normally, only 1 device should sit on 1 IP address. Are you talking about MSTP devices behind a BACnet/IP-MSTP router ?
