### ISSUE TITLE
Sending a directed whois using BAC0

### ISSUE THREAD

**Issue by raghavan97** [ChristianTremblay/BAC0#347]
Hi,

I wanted to know how we can send a directed who-is with a network number using BAC0.

I was doing it using the bacnet-stack binary **_bacwi_**.

root@docker-desktop:/home/rags/bacnet-stack/bin# ./bacwi --mac 192.168.11.234 --dnet 999
;Device   MAC (hex)            SNET  SADR (hex)           APDU
;-------- -------------------- ----- -------------------- ----
  4111100 C0:A8:0B:EA:BA:C0    999   01                   1024
  4111409 C0:A8:0B:EA:BA:C0    999   02                   1024
  4111304 C0:A8:0B:EA:BA:C0    999   03                   1024
  4111305 C0:A8:0B:EA:BA:C0    999   04                   1024
  4111306 C0:A8:0B:EA:BA:C0    999   05                   1024
  4111307 C0:A8:0B:EA:BA:C0    999   06                   1024
  4111904 C0:A8:0B:EA:BA:C0    999   07                   1024
;
; Total Devices: 7

I see that I can pass networks list [999] in discover(), but I am not able to know how to get a directed who-is to a specific IP address.

I am a BAC0 newbie.

**Comment by bbartling** [comment]
You looking to just collect data or make an algorithm to read/write to equipment?

**Comment by raghavan97** [comment]
Hi,

I am looking to read/write to equipment after getting the list of devices.

**Comment by bbartling** [comment]
There maybe some examples to look at in here:
https://github.com/bbartling/Load-Shredder/tree/develop/Load-Shed

**Comment by bbartling** [comment]
I realized I forgot a `device_mapping = []` in the code:


```
import BAC0, time


# define bacnet app
bacnet = BAC0.lite()
time.sleep(2)


devices = bacnet.whois(global_broadcast=True)

device_mapping = []
for device in devices:
    if isinstance(device, tuple):
        device_mapping[device[1]] = device[0]
        print("Detected device %s with address %s" % (str(device[1]), str(device[0])))
print(device_mapping)
print((str(len(device_mapping)) + " devices discovered on network."))
```

**Comment by ChristianTremblay** [comment]
Directed whois is possible with the syntax

```
bacnet.whois("2:*")
```

this makes a whois on network 2

`bacnet,discover()` can also help a lot when exploring the network
