### ISSUE TITLE
run complete version with bokeh server

### ISSUE THREAD

**Issue by bbartling** [ChristianTremblay/BAC0#350]
Am I adding trends in correctly for the complete version?
https://bac0.readthedocs.io/en/latest/connect.html#complete

The dashboard is really nice looking....but no trends to plot:
![image](https://user-images.githubusercontent.com/29737117/191052024-02f2cc2d-e560-4d4a-919e-6606e873a062.png)

No errors when I run this below....am only interested in `analogInput` 2 and 3. In the device they are named `tempUoTwoBalco` and `tempUoThreeBalco`

```
import BAC0
import time,sys


bacnet = BAC0.connect(ip='192.168.0.100/24')

furnace_obj_list = [('analogInput', 2),
                    ('analogInput', 3)]

furnace = BAC0.device('12345:2',
                        201201,
                        bacnet,
                        object_list=furnace_obj_list,
                        segmentation_supported=False)

time.sleep(5)

furnace['tempUoTwoBalco'].chart()
furnace['tempUoThreeBalco'].chart()



def main():

    while True:
        time.sleep(0.01)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        bacnet.disconnect()
        print('disconnected')
        sys.exit(0)
```

**Comment by ChristianTremblay** [comment]
Go in the trends page. And use the drop down took to add the trends you want.

**Comment by bbartling** [comment]
Gosh not seeing a drop down....here?
![image](https://user-images.githubusercontent.com/29737117/191094111-ae9b18d1-256c-433d-bc3f-97b4b3f39e32.png)

**Comment by ChristianTremblay** [comment]
When a device is registered, the objetcs should be visible in a dropdown

![image](https://user-images.githubusercontent.com/6376327/191635389-2611c6ae-1ebe-4451-a140-e8a20668e177.png)

![image](https://user-images.githubusercontent.com/6376327/191635455-ca4bafa5-e4ae-4f73-9737-617efcdc49de.png)
