### ISSUE TITLE
covIncrement is set to 0.15 and not what I set it to (1 in most cases)

### ISSUE THREAD

**Issue by kheldaroz402** [ChristianTremblay/BAC0#366]
HI Christian,
               I'm using 22.09.21 and when I try and set covIncrement it ignores me and defaults to 0.15

`# Analog Inputs
    # Default... percent
    sql = 'SELECT * FROM WebAI_Program.BACnet_Objects_AnalogInput'
    mycursorProgram.execute(sql)
    mydbProgram.commit()
    myresult = mycursorProgram.fetchall()
    for row in myresult:
        # Supplemental with more details, for demonstration
        _new_objects = analog_input(
            name=row['Object_Name'],
            instance=row['Object_Identifier'],
            properties={"units": row['BACnet_Engineering_Units'], "highLimit": row['Max_Pres_Value'], "lowLimit": row['Min_Pres_Value']},
            description=row['Description'],
            presentValue=row['Present_Value'],
            is_commandable=True,
            relinquish_default=row['Relinquish_Default'],
            covIncrement = row['Default_COV'],
        )`

It does show up in yabe but the value is not changing

![2022-11-30 13_37_01-Settings](https://user-images.githubusercontent.com/55415109/204694457-b602289b-098c-48a1-ac68-7c0480393a44.png)

**Comment by ChristianTremblay** [comment]
I'll have to dig into that. Let me know if you find something

**Comment by kheldaroz402** [comment]
Thanks Christian, I'll let you know if I find something

**Comment by ChristianTremblay** [comment]
I think I get it....

`covIncrement` argument must be given through the `properties` dict, like units...

```python
def analog(**kwargs):
    definition = {
        "instance": 0,
        "description": "No description",
        "properties": {
            "units": "percent",
            "eventState": EventState(),
            "covIncrement": 0.15,
        },
        "presentValue": 0,
        "is_commandable": False,
        "relinquish_default": 0,
    }
    return _create(definition, **kwargs)
 ```
    
See https://github.com/ChristianTremblay/BAC0/blob/master/BAC0/core/devices/local/models.py for details

By moving it you should be ok

```python
# Analog Inputs 
# Default... 
# percent sql = 'SELECT * FROM WebAI_Program.BACnet_Objects_AnalogInput' mycursorProgram.execute(sql) mydbProgram.commit() myresult = mycursorProgram.fetchall() for row in myresult: 
# 
# # Supplemental with more details, for demonstration 
_new_objects = analog_input( name=row['Object_Name'], instance=row['Object_Identifier'], properties={"units": row['BACnet_Engineering_Units'], "covIncrement": row['Default_COV'], "highLimit": row['Max_Pres_Value'], "lowLimit": row['Min_Pres_Value']}, description=row['Description'], presentValue=row['Present_Value'], is_commandable=True, relinquish_default=row['Relinquish_Default'], )
```
