### ISSUE TITLE
callback function

### ISSUE THREAD

**Issue by kheldaroz402** [ChristianTremblay/BAC0#367]
HI Christian,

The next issue that I'm having is with the callback function.

it doesn't appear to be working - I've probably done something wrong

`    for row in myresult:
        bacnet.cov(row['Address'], row['Object_Identifer'], row['BACnet_Object_ID'],  lifetime=row['COV_lifetime'], callback=my_callback)`

![2022-11-30 14_10_38-192 168 2 240 - PuTTY](https://user-images.githubusercontent.com/55415109/204699160-f53c75b2-0fe9-4c3f-8833-dab6d4126aaf.png)

Callback function
```
# The Notification will pass a variable named "elements" to the callback
# your function must include this argument

# elements is a dict containing all the information of the COV

def my_callback(elements):
    print(color.YELLOW + "Present value is : {}".format(elements['properties']['presentValue']) + color.END)
    print(color.PURPLE + "Address is : {}".format(elements['address']) + color.END)
    print(color.GREEN + "ObjectID value is : {}".format(elements['objectID']) + color.END)
    print(color.CYAN + "source value is : {}".format(elements['source']) + color.END)
```

it looks like the COV's are working just not the callback

**Comment by ChristianTremblay** [comment]
Hi ! Back from a little screen break, I'll have a look to your case ASAP

**Comment by kheldaroz402** [comment]
Hi Christian,
                  Any progress ?

**Comment by ChristianTremblay** [comment]
Changing the value, I get the COV back

![image](https://user-images.githubusercontent.com/6376327/216742372-65aeb243-2d99-4160-aed7-a51ac1ccb6e0.png)
