### ISSUE TITLE
is it possible to set a customized timeout for the whois?

### ISSUE THREAD

**Issue by Sheng2216** [ChristianTremblay/BAC0#368]
I have some virtual BACnet IP devices running on my laptop(using the Bacnet.Room.Simulator.exe YABE addon), and then I have a Raspberry Pi that sends the whois command to the whole LAN, but sometimes I cannot detect these virtual BACnet IP devices. Is it because the default timeout for whois request is too short?
I see this line:
` iocb.wait()  # Wait for BACnet response`
in the [source code](https://bac0.readthedocs.io/en/latest/_modules/BAC0/core/functions/Discover.html#Discover.whois). Is it possible to adjust it?

**Comment by ChristianTremblay** [comment]
Technically yes, but you shouldn't need to do that. Maybe your network is overloaded ? Or something is blocking somewhere ?
