### ISSUE TITLE
Improvements to GetIPAddr

### ISSUE THREAD

**Issue by ChristianTremblay** [ChristianTremblay/BAC0#37]
@kjlockhart proposed some changes to GetIPAddr
It was not working on windows so some work has to be done to validate.
I use the previous file in the meantime. I will study the proposition.

**Comment by kjlockhart** [comment]
Ok.
I am unable to test Windows versions.  All my development is done on Ubuntu 16.04+.
The last Windows development I did was years ago - on Win 7.

**Comment by ChristianTremblay** [comment]
Develop branch (next release) contains a fix to GetIPAddr... Works better on Ubuntu
