### ISSUE TITLE
writeMultiple fails with "bacpypes.errors.InvalidTag: errorType expected opening tag 0"

### ISSUE THREAD

**Issue by CrisCodesCrap** [ChristianTremblay/BAC0#380]
When I try executing the ```writeMultiple``` method the process throws the following error:
![Screenshot_1](https://user-images.githubusercontent.com/90000349/221434366-5e968fef-797a-4e30-8c12-27e09164c914.png)
I even tried a minimal reproduction with the following setup:
```
*requirements.txt*
BAC0==22.9.21
bacpypes==0.18.6
colorama==0.4.6
netifaces==0.11.0
pytz==2022.7.1
```

```
*main.py*
from BAC0 import lite

bac = lite()

bac.writeMultiple("192.168.0.128:50286", ['analogValue 1 presentValue 100'])
# bac.readMultiple()
```
My python version is 3.11
![Screenshot_2](https://user-images.githubusercontent.com/90000349/221435186-4af22a81-5f5c-4fa0-b2c9-86fa49eb3bb2.png)

Any help would be greatly appreciated!

Tried it with 
![image](https://user-images.githubusercontent.com/90000349/221435200-f79703cc-1b80-4387-855c-ac45b9a129c2.png)
 and the same setup as before.
Does not work as well.

**Comment by CrisCodesCrap** [comment]
Tried it with 
![image](https://user-images.githubusercontent.com/90000349/221435200-f79703cc-1b80-4387-855c-ac45b9a129c2.png)
 and the same setup as before.
Does not work as well.

**Comment by ChristianTremblay** [comment]
I'm concerned about the `bac.readMultiple()` part

**Comment by CrisCodesCrap** [comment]
This is a mistake in the example.
It does not work either way, any ideas on how we can tackle it?

**Comment by ChristianTremblay** [comment]
Ok. 
And this BACnet device is running on port 50286 ? Unusual 

Try keeping only the IP.

**Comment by CrisCodesCrap** [comment]
The device running on port 50286 is a virtual device from Yabe's add-ons.
From what I think the issue may be is regarding the parser of bacpypes and how it handles arrays of strings for this specific method.

**Comment by ChristianTremblay** [comment]
Array of strings ?

Strings are weird in BACnet,.... I haven't work on writeMultiple for string values but if you look [here](https://github.com/ChristianTremblay/BAC0/blob/master/BAC0/core/functions/Text.py) you will see tools to write text value in BACnet.

This is used by the `update_description` method of devices....[here](https://github.com/ChristianTremblay/BAC0/blob/master/BAC0/core/devices/Device.py#L795)

**Comment by CrisCodesCrap** [comment]
I am talking about the writeMultiple method on this page https://bac0.readthedocs.io/en/latest/write.html

**Comment by CrisCodesCrap** [comment]
I'll test the dev branch as soon as I get access to my machine
