### ISSUE TITLE
DCC_Time duration of disable

### ISSUE THREAD

**Issue by Chris-Wang-bjc** [ChristianTremblay/BAC0#383]
hello, I used “Device Communication Control” service to disable the device, but the "timeDuration" argument didn't work.
Here is my code:
bacnet.dcc(address='address of device', duration=1, state='disable', password='password')

I am sure that all the parameters in this request are correctly configured and the request is sent correctly.
But when I checked the Wireshark logs, I didn't see the "timeDuration" parameter.
![image](https://user-images.githubusercontent.com/53858616/223380632-a67dfbe6-198a-45c8-8c1e-bc863367efb1.png)

And the device failed to return to a working state after 1 minute.

**Comment by Chris-Wang-bjc** [comment]
I already solved it. Please ignore it.

**Comment by ChristianTremblay** [comment]
And what what the problem ? I'm curious

**Comment by Chris-Wang-bjc** [comment]
Sorry, this problem is due to other libraries I used, not BAC0, thanks!
