### ISSUE TITLE
BAC0 can only discover virtual device from BOSS a Softdel BACner/IP Simulation System in the first few times

### ISSUE THREAD

**Issue by 11208** [ChristianTremblay/BAC0#384]
I have simulated BACNET using BOSS a Softdel BACner/IP Simulation System. 
I created a basic python app like
```
import BAC0

def main():
    bacnet = BAC0.connect(ip='192.168.1.156/24')
    bacnet.discover()
    print(bacnet.devices)

if __name__ == "__main__":
    main()
```

The first time I run the app device show up, 
<img width="992" alt="Screen Shot 2566-03-22 at 08 25 57" src="https://user-images.githubusercontent.com/38026488/226778546-8a97dca9-8b50-4bd9-a285-87e4e055eeaa.png">

but when I run it for the second time or third time no device show up.
<img width="994" alt="Screen Shot 2566-03-22 at 08 26 06" src="https://user-images.githubusercontent.com/38026488/226778581-73ed8898-86d2-401b-be89-412a1263ee43.png">

**Comment by 11208** [comment]
I test with nmap and got this.
```
sudo nmap --script bacnet-info --script-args full=yes -sU -n -sV -p 47808 192.168.1.156
```
<img width="667" alt="Screen Shot 2566-03-22 at 10 38 51" src="https://user-images.githubusercontent.com/38026488/226796169-3030d3b8-0b45-4777-b72d-93df38327d7c.png">

The is close but the simulator is still running. 
I also use Thingsboard Gateway to pull data and the data is save to db normally.
Why can BAC0 detect when the state is close.

**Comment by 11208** [comment]
Simulator issue

**Comment by 11208** [comment]
I tested with two BACnet simulators. One from SoftDEL and one from YABE AddOn

Step:
1. Start SoftDEL BOSS, Then call whois() and get response back.
2. Wait for a while and call whois again, empty response.
3. Start YABE Simulator Then call whois() and get response for SoftDEL and YABE back.

Seems like after a while the simulator don't listen or want to answer, unless another BACnet application start and trigger port 47808 or something.

Do we have any function that trigger BACNET to start answering whois or discover function again?

**Comment by ChristianTremblay** [comment]
once BAC0 runs (and keep running) it acts as a BACnet device and will respond to I-Am ...

for your tests, just load a python interpreter and run your code. It will keep BAC0 running and it'll be easier to find what is going on

**Comment by 11208** [comment]
I did tried python interpreter and only able to get the response when calling discover() or whois() for a few times after the Simulator started then getting empty response as before. May I have to find a work around to get device list when calling those two function after time passed.

My intension is to query a device list and its properties using BAC0 when function call.

**Comment by 11208** [comment]
Seems like my issue is related to #331

**Comment by 11208** [comment]
Here is the screen shot of wireshark.
<img width="1192" alt="Screen Shot 2566-03-29 at 09 43 57" src="https://user-images.githubusercontent.com/38026488/228413153-8fdf806f-7d38-416d-99b3-8bb32d325042.png">

Does anyone have an idea on how to fix this?

**Comment by bbartling** [comment]
I never have issues with using BAC0 but I am always in the field on real BACnet devices on real hardware where there is no VM's or networking jerry rigging to accommodate running multiple BACnet devices on one device.

Something like this always work for me on real equipment:


```
import BAC0, time


# define bacnet app
bacnet = BAC0.lite()
time.sleep(2)


# generates all BACnet addresses some are not VAV boxes
devices = bacnet.whois(global_broadcast=True)

for device in devices:
    if isinstance(device, tuple):
        device_mapping[device[1]] = device[0]
        print("Detected device %s with address %s" % (str(device[1]), str(device[0])))
print(device_mapping)
print((str(len(device_mapping)) + " devices discovered on network."))
```
