### ISSUE TITLE
Why can I not import this from BAC0

### ISSUE THREAD

**Issue by KijanDaniel** [ChristianTremblay/BAC0#394]
The error is: Traceback (most recent call last):
  File "c:\Users\DanielKi\Desktop\BacNet Simulation\testDevices.py", line 5, in <module>
    from BAC0.core.devices.local import (
ImportError: cannot import name 'analog_input' from 'BAC0.core.devices.local' (C:\Users\DanielKi\AppData\Roaming\Python\Python310\site-packages\BAC0\core\devices\local\__init__.py)

This was taken from your example code for creating objects

**Comment by ChristianTremblay** [comment]
Doc needs to be updated.
