### ISSUE TITLE
How to write the Value of property "state-text" with parameter "array index"?

### ISSUE THREAD

**Issue by Chris-Wang-bjc** [ChristianTremblay/BAC0#397]
Hi, all
I want to write the value of property "state-text", the type of this property is a Array list including three "CharacterString" value. Such as ['?','?','?']. When writing the value, I need to pass the "array index" parameter, however, the currently provided function does not seem to support passing this parameter. So I want to know, when I write this value, how can I pass this parameter in? Or whether I can customize the parameters of this function? Looking forward to your reply, thanks!
![image](https://github.com/ChristianTremblay/BAC0/assets/53858616/fef03247-53eb-49dd-a5ba-35e26be4372c)

**Comment by Chris-Wang-bjc** [comment]
I want the function "write" to be able to pass in the arguments that I need, thanks

**Comment by bbartling** [comment]
what error do you get?

**Comment by Chris-Wang-bjc** [comment]
No error, I'm just wondering how I can pass the parameter "array index" into the write function.

**Comment by Chris-Wang-bjc** [comment]
This may not be an issue, but I have no way to contact you and can only ask you some questions in this way.

**Comment by Chris-Wang-bjc** [comment]
I have solved it, so I close this issue, thanks very much!

**Comment by ChristianTremblay** [comment]
It is perfectly fine to ask questions this way. 

What would be very nice would be you post the answer you found. This way, other will find it if they ever look for it. 

And eventually, it gives some "documentation" material. 

Thanks
