### ISSUE TITLE
How to find out whether a BACnet device is also a router?

### ISSUE THREAD

**Issue by tontonialberto** [ChristianTremblay/BAC0#413]
Hello again,

I encountered an issue while performing a series of who-is requests to BACnet devices over a local network.

I would like to be able to determine whether a particular BACnet device is also a BACnet router.

Any simple way to do this using BAC0?

Thanks in advance,

Alberto

**Comment by ChristianTremblay** [comment]
I usually take the reverse path

`bacnet.who_is_router_to_network(2000)`

**Comment by tontonialberto** [comment]
Where do the number "2000" come from?

**Comment by ChristianTremblay** [comment]
It is just an example, given that you would be looking for the network number 2000
