### ISSUE TITLE
Issue with exiting then restarting BAC0 script

### ISSUE THREAD

**Issue by dqcontrols** [ChristianTremblay/BAC0#428]
Hi,

I have a script that connects to a network, defines a controller, then reads from and writes to the controller points every 60 seconds. It all works well, and I use the functions below to safely exit the code with a Ctrl-C input.

def cleanup():
    print('Cleaning up...')
    logging.info('Cleaning up program!')
    for index, row in dq_control_points.points.iterrows():
        write_object_point = row['dqcontrol Point Name']
        write_objectID = row['objectID']
        write_point_value = row['Point Value']
        equipment_value = row['Equipment']
        if write_objectID != 'N/A':
            bacnet.write(config['DEVICE']['deviceip'] + ' ' + write_objectID[0] + ' ' + str(write_objectID[1]) + ' presentValue ' + 'null' + ' - ' + str(config['DEVICE']['dqcontrolpriority']))
            logging.info('System queued to close! Writing NULL to priority 14.')
    bacnet.disconnect()
    logging.info('Disconnecting from BACNet Network.')
    logging.info('Ending logging session.')
    logging.shutdown()
    return None
    
def signal_handler(sig, frame):
    # Handle Ctrl+C or other signals here
    print("Received signal:", sig)
    logging.info('Recieved signal: %s', str(sig))
    cleanup()
    sys.exit(0)
    return None
    
    
 The issue occurs when I restart the code again without clearing the console. The code runs until it reaches the point where the code attempts to write to the points in the controller:
 bacnet.write(config['DEVICE']['deviceip'] + ' ' + write_objectID[0] + ' ' + str(write_objectID[1]) + ' presentValue ' + write_point_value + ' - ' + config['DEVICE']['dqcontrolpriority'])

At which point the following error occurs:
 <class 'BAC0.core.io.IOExceptions.ApplicationNotStarted'>: BACnet stack not running - use startApp()
 
 I'm not clear on the exact process of exiting and then restarting BAC0. Any help would be appreciated.

**Comment by ChristianTremblay** [comment]
Looks like Python is having difficulty to release the socket maybe ? I haven't had this scenario in mind when making BAC0 as it's made to be a BACnet device that live on the network like any other device... not shutting down then restarting every time.

I usually create app acting like services, that run all the time, and a recurring task that does the work.
