### ISSUE TITLE
Is it possible to monitor EventEnrollment objects?

### ISSUE THREAD

**Issue by marganellim** [ChristianTremblay/BAC0#429]
Hello

Is it possible to monitoring or read the status of eventEnrollment points? 
I dont fully understand how eventEnrollments differ from regular points, such as AI's, BI's etc but I have a use case to monitor a collection of BAS alarms that are eventEnrollment type. 

Thanks for any information

**Comment by marganellim** [comment]
Nevermind. You can monitoring eventEnrollment points but you have to use the eventState property. My bad

**Comment by bbartling** [comment]
what is an eventEnrollment point? Or where is it used??

**Comment by marganellim** [comment]
> what is an eventEnrollment point? Or where is it used??

An eventEnrollment is a BACnet object, often used for alarms. It's defined in section 12.12 of the BACnet specificiation.

**Comment by bbartling** [comment]
okay an alarm defined in BACnet. Can you setup BACnet alarms in BAC0 or only to monitor?

**Comment by marganellim** [comment]
I'm not sure. I'm not the right person to ask. I just started using BAC0 earlier this year.
