### ISSUE TITLE
Simulated device not sending COV

### ISSUE THREAD

**Issue by Weird-Banana** [ChristianTremblay/BAC0#442]
Hi, I am using BAC0 22.9.21 to simulate a BACnet device with different AnalogInput points.
In the same script I have a function that randomly changes the present value of these points, till here everything works fine.

I have now created another script with BAC0 which reads the simulated device and use bacnet.cov(...) to subscribe to my simulated points. However, I am not receiving notifications on when the present value changes.

Is there anything I need to add to my simulator to make my points subscribable?

**Comment by Weird-Banana** [comment]
I have removed the lifetime parameter from bacnet.cov and now it seems like that the callback is always getting triggered although there was no COV.

**Comment by ChristianTremblay** [comment]
The local object in a BAC0 instance do not support COV yet. The work done covers receiving COV... not sending.
I think it'll be possible with the next iteration using bacpypes3.

**Comment by Weird-Banana** [comment]
Thanks for the clarification, I thought I was doing something with the simulation part :)
