### ISSUE TITLE
BAC0 running in docker is not able to discover devices in network

### ISSUE THREAD

**Issue by shivangishakya** [ChristianTremblay/BAC0#449]
I am not able to discover bacnet devices if runs BAC0 script in docker. It is working fine in local machine (windows). Tried: network_mode = host and creating a network with gateway as my router's IP.

**Comment by ChristianTremblay** [comment]
This is a common issue with docker as UDP broadcast are not passing through...

Discovery will fail but I think you will be able to connect directly to a device (unicast)

**Comment by shivangishakya** [comment]
Any way of bacnet discovery?

**Comment by ChristianTremblay** [comment]
Using docker, it's hard and I haven't done a lot of tests.

Last time I worked on that, I found this : https://www.youtube.com/watch?v=bKFMS5C4CG0

But I haven't had time to fully test everything. Basically, it really is down to the UDP broadcast that need to travel to the container and from the container.
