### ISSUE TITLE
Unable to Install BAC0 on windows

### ISSUE THREAD

**Issue by spadilam** [ChristianTremblay/BAC0#45]
Team,

I am trying to use python 3.6 version and when trying to install BACO. I am facing problem with the installation.

Could you please help us out in this process.

Regards,
Srinivas Padilam.

**Comment by henkwitte** [comment]
Install anaconda (https://www.continuum.io/downloads) open an anaconda prompt (see start menu, anaconda3, anaconda prompt) and run pip install BAC0

Worked for me!

Henk

**Comment by ChristianTremblay** [comment]
If @henkwitte solution, please provide more details.
But I'm pretty sure Anaconda will work.

**Comment by spadilam** [comment]
Hi Team,
Do I need to install anaconda as well. 
 I trying to use the libraries directly in python3.6 and installed bacpypes and bokeh packages ...
After that when trying to intall the BAC0 I am getting issue with VBox ...

Please suggest me the solution. I want to use with solution without anaconda package.

**Comment by ChristianTremblay** [comment]
It's due to the new bokeh version. I'll put a new version on pypi soon. 

In the meantime you can use the develop branch and it will work.

**Comment by ChristianTremblay** [comment]
@spadilam  Have you had the chance to make it work ?
If so, I'll close the issue.

**Comment by gandhamyamini467** [comment]
Hello im not able to work it out?
Can you please suggest me how to install BAC0.I have installed anaconda too,but of no use.Please help me with this
![help](https://user-images.githubusercontent.com/47096139/55054486-16362e00-5086-11e9-839b-9738deb7bd28.png)

**Comment by ChristianTremblay** [comment]
run `python setup.py install` in BAC0-master.
Or simply use `pip install BAC0` anywhere if you don' need to modify code.
