### ISSUE TITLE
Adding schedule and accumulator to object factory

### ISSUE THREAD

**Issue by yujia21** [ChristianTremblay/BAC0#457]
Hi, I'm interested in having schedule and accumulator objects in `BAC0.core.devices.local.models`, is there any guidelines to be followed to contribute or can I follow the patterns of the other object types and open a PR?

**Comment by ChristianTremblay** [comment]
Very few, everything is in bacpypes repo. I usually base my work on examples provided by Joel.

Please note that I will soon switch to a new version of BAC0 using BACpypes3 and I will not continue the development of legacy BAC0 based on bacpypes legacy. Have a look to the async branch (https://github.com/ChristianTremblay/BAC0/tree/async)
