### ISSUE TITLE
Connect to Bacnet MSTP device on through router on another subnet 

### ISSUE THREAD

**Issue by viraj-96** [ChristianTremblay/BAC0#463]
Hi I have a bit of a weird situation. Im on a corporate network and my local machine is on a different subnet than the Bacnet router/controller(Trane SC+ if that helps). 

I am able to connect directly to the router and read points on it, however I am unable to read points or connect to MSTP devices on the other side of the router that are visible on Yabe. Any ideas on how to make this work?

```
my_ip = '10.45.12.150'
bbmdIP = '10.45.52.20:47808' # ip of router
bacnet = BAC0.connect(ip=my_ip, bbmdAddress=bbmdIP)
```

The discover function doesn't seem to find anything either.  
![image](https://github.com/user-attachments/assets/8538348b-0f95-49af-b86b-8b7b4d5b4bb3)

Connecting to Router works
![image](https://github.com/user-attachments/assets/0e97337c-bcf3-4dd8-8b9a-603a75f1e965)

Cant connect using MSTP formatting 
![image](https://github.com/user-attachments/assets/07684204-ec60-4cd6-9afd-6166ad2807fc)

**Comment by mirhamza708** [comment]
did you try this?
```
bacnet = BAC0.connect(ip='Your IP / your subnet mask', port='port', deviceId='some random device ID')
# BAC0.connect(ip='10.45.12.15/24', port='47808', deviceId='123654')
bacnet.discover()
```

**Comment by viraj-96** [comment]
Was able to get this working on mu side. I had forgot to specify bbmdTTL in my initial connection, now I can see all devices. 
Thanks
