### ISSUE TITLE
Cannot resolve the import "BAC0. Core. Devices. Local. Models"

### ISSUE THREAD

**Issue by FGHQW** [ChristianTremblay/BAC0#470]
run \tests\manualtest_cov.py   Cannot resolve the import "BAC0. Core. Devices. Local. Models"

**Comment by ChristianTremblay** [comment]
Manual tests files haven't been migrated to async. 

Only test_xyz works and are used in CICD

**Comment by ChristianTremblay** [comment]
I migrated 

- https://github.com/ChristianTremblay/BAC0/blob/main/tests/manual_test_cov.py
- https://github.com/ChristianTremblay/BAC0/blob/main/tests/manual_test_create_device.py

if you want to play
