### ISSUE TITLE
Points not detected by YABE

### ISSUE THREAD

**Issue by SIDRAGNEEL** [ChristianTremblay/BAC0#478]
Hello, after running the create device test code with a modified add point function, YABE doss not show any points but a Network port. Is this a code issue or a YABE issue ?
 ![IMG-20240919-WA0003.jpg](https://github.com/user-attachments/assets/f8533d9d-08a5-4f0a-86f6-0a0e67d9e8d4)

![IMG-20240919-WA0002.jpg](https://github.com/user-attachments/assets/81de587c-56f1-4302-8743-636da446865f)

The point value can be modified and read according to output. 
![IMG-20240919-WA0004.jpg](https://github.com/user-attachments/assets/167286bb-0311-43aa-a5f7-f8a5286908a5)

**Comment by ChristianTremblay** [comment]
The script you show me creates 2 bacnet devices. One on 0xBAC0, the other one on 0xBAC1
The one with all the points added is on port 47809 (0xBAC1)
The one you look at on YABE is the one created first in the script, which I use for connecting to devices when testing.

If you want to create 1 device, use only the first async with 

You should also remove time.sleep and maybe replace that with an asyncio.sleep or you will pause the execution of the script everytime you call sleep.

**Comment by SIDRAGNEEL** [comment]
> The script you show me creates 2 bacnet devices. One on 0xBAC0, the other one on 0xBAC1
> The one with all the points added is on port 47809 (0xBAC1)
> The one you look at on YABE is the one created first in the script, which I use for connecting to devices when testing.
> 
> If you want to create 1 device, use only the first async with 
> 
> You should also remove time.sleep and maybe replace that with an asyncio.sleep or you will pause the execution of the script everytime you call sleep.

Thanks a lot. Is there a way to create two independent devices that  are from the same IP , perhaps using different ports, to read /write on the other devices ?

**Comment by ChristianTremblay** [comment]
https://github.com/ChristianTremblay/BAC0/blob/main/tests/manual_test_create_device.py
