### ISSUE TITLE
static ip issues

### ISSUE THREAD

**Issue by Jzhenli** [ChristianTremblay/BAC0#484]
Hi, My device use static IP, and when run the scripts [manual_test_create_device.py](https://github.com/ChristianTremblay/BAC0/blob/main/tests/manual_test_create_device.py), it will raise error as follows，would u help to check what's the problem?

<img width="971" alt="1727246310823" src="https://github.com/user-attachments/assets/47d39f5b-cfa1-44d2-b4a0-dac6f64e40ac">

**Comment by ChristianTremblay** [comment]
provide the IP manually, when not provided, I try to ping google to find the socket...
```python
myip = '192.168.1.200/24',
async def main():
    # We'll use 3 devices plus our main instance
    async with BAC0.start(ip=myip , 'localObjName="bacnet") as bacnet:
        async with BAC0.start(ip=myip ,port=47809, localObjName="App1") as device_app:
            async with BAC0.start(ip=myip ,port=47810, localObjName="App2") as device30_app:
                async with BAC0.start(ip=myip ,port=47811, localObjName="App3") as device300_app:
                    add_points(2, device_app)
                    add_points(3, device30_app)
                    add_points(4, device300_app)
[...]
```
