### ISSUE TITLE
bacnet.read For Device Level Properties

### ISSUE THREAD

**Issue by TheeHappyCoder** [ChristianTremblay/BAC0#489]
Hi, I am trying to read device level properties like these for example :  device_properties = ['objectIdentifier', 'objectName', 'vendorName', 'vendorIdentifier', 'modelName', 'systemStatus', 'description'] but I do not wish to use BAC0.devce method as this automatically builds the points list and takes longer, especially if there are multiple devices and they have a lot of points. 

I am attempting to use the bacnet.read but I only get the device instance and address using this method, any suggesstions as to how I can go about this?

**Here is my code snippet I use witht the BAC0.device (which works but builds the points list by default) :** 

```python
@app.route('/api/discover_device_info', defaults={'device_instance': None}, methods=['GET'])
@app.route('/api/discover_device_info/<device_instance>', methods=['GET'])
@limiter.limit("5 per 2 seconds")
def discover_device_info(device_instance=None):
    global global_bacnet

    def generate():
        try:
            if global_bacnet is None:
                yield "data: {}\n\n".format(json.dumps({"error": "BACnet not initialized. Set IP first."}))
                return

            all_devices = global_bacnet.whois()
            new_devices = [device for device in all_devices if device[1] not in connected_devices.keys()]

            if device_instance:
                new_devices = [device for device in new_devices if device[1] == int(device_instance)]

            if not new_devices:
                yield "data: {}\n\n".format(json.dumps({"error": "No new devices found"}))
                yield "data: {}\n\n".format(json.dumps({"completion": True}))
                return

            # Basic device properties including description
            device_properties = ['objectIdentifier', 'objectName', 'vendorName', 'vendorIdentifier', 'modelName', 'systemStatus', 'description']

            for device in new_devices:
                device_address, loop_device_instance = device
                device_info = {"address": device_address, "instance": loop_device_instance}

                try:
                    my_device = BAC0.device(device_address, loop_device_instance, global_bacnet, poll=0)

                    # Read only basic device properties (including description)
                    for prop in device_properties:
                        try:
                            prop_value = my_device.read_property(prop)
                            device_info[prop] = prop_value
                        except Exception as e:
                            logging.info(f"No data found for property {prop} on device {loop_device_instance}")

                    my_device.disconnect()

                except Exception as e:
                    logging.error(f"Error reading device information for device {loop_device_instance}: {e}")

                yield "data: {}\n\n".format(json.dumps(device_info))

            yield "data: {}\n\n".format(json.dumps({"completion": True}))

        except Exception as e:
            logging.error(f"Error in discover_device_info: {e}")
            yield "data: {}\n\n".format(json.dumps({"error": str(e)}))
            yield "data: {}\n\n".format(json.dumps({"completion": True}))

    return Response(stream_with_context(generate()), content_type='text/event-stream')
```    
    **I tried this but it did not work :** 

```python    
@app.route('/api/discover_device_info', defaults={'device_instance': None}, methods=['GET'])
@app.route('/api/discover_device_info/<device_instance>', methods=['GET'])
@limiter.limit("5 per 2 seconds")
def discover_device_info(device_instance=None):
    global global_bacnet

    def generate():
        try:
            if global_bacnet is None:
                yield "data: {}\n\n".format(json.dumps({"error": "BACnet not initialized. Set IP first."}))
                return

            # Discover new devices
            all_devices = global_bacnet.whois()
            new_devices = [device for device in all_devices if device[1] not in connected_devices.keys()]

            if device_instance:
                new_devices = [device for device in new_devices if device[1] == int(device_instance)]

            if not new_devices:
                yield "data: {}\n\n".format(json.dumps({"error": "No new devices found"}))
                yield "data: {}\n\n".format(json.dumps({"completion": True}))
                return

            # Basic device properties you want to fetch
            device_properties = ['objectIdentifier', 'objectName', 'vendorName', 'vendorIdentifier', 'modelName', 'systemStatus', 'description']

            for device in new_devices:
                device_address, loop_device_instance = device
                device_info = {"address": device_address, "instance": loop_device_instance}

                try:
                    # Instead of using BAC0.device, read the desired properties directly
                    for prop in device_properties:
                        try:
                            prop_value = global_bacnet.read(f'device:{loop_device_instance} {prop}', device_address)
                            device_info[prop] = prop_value
                        except Exception as e:
                            logging.info(f"No data found for property {prop} on device {loop_device_instance}")

                except Exception as e:
                    logging.error(f"Error reading device information for device {loop_device_instance}: {e}")

                yield "data: {}\n\n".format(json.dumps(device_info))

            yield "data: {}\n\n".format(json.dumps({"completion": True}))

        except Exception as e:
            logging.error(f"Error in discover_device_info: {e}")
            yield "data: {}\n\n".format(json.dumps({"error": str(e)}))
            yield "data: {}\n\n".format(json.dumps({"completion": True}))

    return Response(stream_with_context(generate()), content_type='text/event-stream')
    
```

**Comment by ChristianTremblay** [comment]
I would 

```python
my_device = await BAC0.device(device_address, loop_device_instance, global_bacnet, object_list = [('device',loop_device_instance),], poll=0)
await mydevice.update_bacnet_properties()
```

now you have access to `mydevice.properties.bacnet_properties`

by giving a empty custom object list, it's fast. 

(legacy version...remove the await statements)

**Comment by TheeHappyCoder** [comment]
Awesome, thank you. I implemented this into my code : 

    def generate():
        try:
            if global_bacnet is None:
                yield "data: {}\n\n".format(json.dumps({"error": "BACnet not initialized. Set IP first."}))
                return

            # Discover new devices
            all_devices = global_bacnet.whois()
            new_devices = [device for device in all_devices if device[1] not in connected_devices.keys()]

            if device_instance:
                new_devices = [device for device in new_devices if device[1] == int(device_instance)]

            if not new_devices:
                yield "data: {}\n\n".format(json.dumps({"error": "No new devices found"}))
                yield "data: {}\n\n".format(json.dumps({"completion": True}))
                return

            device_properties = ['objectName','description']

            for device in new_devices:
                device_address, loop_device_instance = device
                device_info = {"address": device_address, "instance": loop_device_instance}

                try:
                    my_device = BAC0.device(device_address, loop_device_instance, global_bacnet, object_list=[('device', loop_device_instance)], poll=0)

                    my_device.update_bacnet_properties()  
                    bacnet_properties = my_device.properties.bacnet_properties

                    logging.info(f"Fetched properties for device {loop_device_instance}: {bacnet_properties}")
                    print(f"Fetched properties for device {loop_device_instance}: {bacnet_properties}")

                    for prop in device_properties:
                        prop_value = bacnet_properties.get(prop, 'No data found')  
                        device_info[prop] = prop_value

                    logging.info(f"Device info returned for device {loop_device_instance}: {device_info}")
                    print(f"Device info returned for device {loop_device_instance}: {device_info}")

                    my_device.disconnect()

                except Exception as e:
                    logging.error(f"Error reading device information for device {loop_device_instance}: {e}")

                yield "data: {}\n\n".format(json.dumps(device_info))

            yield "data: {}\n\n".format(json.dumps({"completion": True}))

        except Exception as e:
            logging.error(f"Error in discover_device_info: {e}")
            yield "data: {}\n\n".format(json.dumps({"error": str(e)}))
            yield "data: {}\n\n".format(json.dumps({"completion": True}))

    return Response(stream_with_context(generate()), content_type='text/event-stream')
    
    And now it only returns the device properties like so : 
    
    Fetched properties for device 4079771: {'objectIdentifier': ('device', 4079771), 'objectName': 'RoomController.Simulator', 'objectType': 'device', 'systemStatus': 'operational', 'vendorName': 'F. Chaxel, Thanks to Morten Kvistgaard, MIT licence, 2015', 'vendorIdentifier': 61440, 'modelName': 'Room_FC_2014', 'firmwareRevision': '0.1.0', 'applicationSoftwareVersion': '0.1.0', 'protocolVersion': 1, 'protocolRevision': 14, 'protocolServicesSupported': [0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0], 'protocolObjectTypesSupported': [1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'objectList': [('device', 4079771), ('analogInput', 0), ('analogInput', 1), ('analogInput', 2), ('analogValue', 0), ('analogValue', 1), ('analogValue', 2), ('analogValue', 3), ('characterstringValue', 1), ('binaryValue', 0), ('binaryValue', 1), ('multiStateValue', 0), ('multiStateValue', 1)], 'maxApduLengthAccepted': 1476, 'segmentationSupported': 'segmentedBoth', 'apduTimeout': 3000, 'numberOfApduRetries': 3, 'deviceAddressBinding': [], 'databaseRevision': 0, 'description': 'Free RoomController Simulator, F. Chaxel 2015', 'location': 'FR'}
Device info returned for device 4079771: {'address': '0xc0a801eee789', 'instance': 4079771, 'objectName': 'RoomController.Simulator', 'description': 'Free RoomController Simulator, F. Chaxel 2015'}
